config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'themes#index'

  resources :themes, only: %i[index show], param: :name do
    resources :variants, param: :variant, only: :show
  end
end

app/models/theme.rb
# frozen_string_literal: true

require 'English'
require_relative '../../lib/errors'
require_relative '../../lib/logging'

class Theme < ApplicationRecord
  has_many :variants, dependent: :destroy

  validates :name, presence: true, uniqueness: true # rubocop:disable Rails/UniqueValidationWithoutIndex

  scope :perfect, -> { joins(:variants).distinct }

  CMD = "emacsclient -s peach -n -c -eval '(fetch-and-load-theme \"%s\")'"

  def to_param
    name
  end

  def older_than?(version)
    if self.version
      d1 = make_datetime(self.version)
      d2 = make_datetime(version)

      d1 < d2
    else
      true
    end
  end

  def update_screenshots!(new_attrs)
    pid = nil

    begin
      Timeout.timeout(90) do
        cmd = format(CMD, name)
        PeachMelpa::Log.info(name) { "going to launch #{cmd}" }
        pid = Kernel.spawn cmd
        Process.wait pid

        # rubocop:disable Style/NegatedIf, Style/Not
        raise PeachMelpa::Errors::EmacsError if not $CHILD_STATUS.success?

        # rubocop:enable Style/NegatedIf, Style/Not

        PeachMelpa::Log.info(name) { 'success! picking up screenshots...' }
      end

      capture_artifacts! new_attrs
    rescue Timeout::Error
      # the process hung
      PeachMelpa::Log.info(name) do
        'the Emacs process is taking too much time, killing it now.'
      end
      Process.kill 'TERM', pid
    rescue PeachMelpa::Errors::NoThemeScreenshotsFolder => e
      PeachMelpa::Log.info(name) do
        "#{e.message}: moving on..."
      end
    rescue PeachMelpa::Errors::EmacsError => e
      PeachMelpa::Log.info(name) do
        "the Emacs process exited with an unknown error: #{e.inspect}"
      end
      # something bad happened in Emacs
    end
  end

  def devise_variants(screenshots)
    endings = Regexp.new("_(#{PeachMelpa::EXTENSIONS.values.join('|')}).png$")

    screenshots.map { |s| s.gsub(endings, '') }.uniq
  end

  def radical
    extras = %w[color theme themes]

    name
      .split('-')
      .reject { |p| extras.include?(p) }
      .join('-')
  end

  def capture_artifacts!(new_attrs)
    Dir.chdir PeachMelpa::Parsing::SCREENSHOT_FOLDER do
      raise PeachMelpa::Errors::NoThemeScreenshotsFolder unless Dir.exist? name

      Dir.chdir(name) do
        files = Dir.glob('*')

        PeachMelpa::Log.info(name) { 'deleting all variants' }
        variants.destroy_all

        variant_names = devise_variants(files)
        PeachMelpa::Log.info(name) { "found variants: #{variant_names}" }

        variant_names.each do |name|
          PeachMelpa::Log.info(self.name) { "capturing: #{name}" }
          variant = variants.find_or_create_by(name: name)
          variant.parse!
        end

        PeachMelpa::Log.info(self.name) { 'updating attributes...' }
        update!(new_attrs)

        PeachMelpa::Log.info(self.name) { 'cleaning up screenshots...' }
        File.delete(*files)

        PeachMelpa::Log.info(self.name) { 'done.' }
      end

      Dir.rmdir(self.name)
    end
  end

  def multi?
    variants.count > 1
  end

  def thumbnail
    @lisp = Mode.find_by(name: 'Lisp')
    variants.first.screenshots.find_by(mode: @lisp)
  end

  def preview
    factor = 2.49
    dimensions = "#{1600 / factor}x#{1200 / factor}"

    # FIXME: figure out if this operation is cached or not
    thumbnail.image.variant(gravity: 'SouthWest', crop: "#{dimensions}+0+0", resize: '300x300^')
  end

  def make_datetime(version)
    d, t = version.split('.')
    t.prepend '00' if t.length <= 2 # midnight minutes

    date = Date.parse d
    time = t.insert(-3, ':')

    DateTime.parse("#{date} #{time}")
  end

  def version_to_datetime
    make_datetime(version)
  end
end

app/controllers/themes_controller.rb
# frozen_string_literal: true

class ThemesController < ApplicationController
  before_action :set_theme,
                :set_variant,
                :set_mode,
                :set_pagination,
                only: %i[show]

  PAGE_SIZE = 12
  @lisp = Mode.find_by(name: 'Lisp')

  # GET /themes
  # GET /themes.json
  def index
    set_page_title_for 'home'
    @page = (request.params[:page] || 1).to_i

    redirect_to root_path, notice: t('errors.negative_offset') if @page < 1

    offset = (@page - 1) * PAGE_SIZE

    @count = Theme.perfect.count

    # this logic hurts
    if @page > 1
      @previous = if @page == 2
                    themes_path
                  else
                    themes_path(page: @page - 1)
                  end
    end

    @next = themes_path(page: @page + 1) unless offset + PAGE_SIZE >= @count

    @themes = Theme
              .perfect
              .offset(offset)
              .limit(PAGE_SIZE)
              .order(version: :desc)
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
    set_page_title_for 'show',
                       name: @theme.radical,
                       description: @theme.description.present? && ": #{@theme.description}"

    @screenshot = @variant.screenshots.find_by(mode: @mode)
    @url = @theme.url.nil? ? "https://melpa.org/#/#{@theme.name}" : @theme.url
  end

  private

  def set_theme
    name = params[:name]
    @theme = Theme.find_by(name: name)

    if @theme.nil?
      redirect_to root_path, notice: t('errors.not_found', name: name)
    elsif @theme.variants.empty?
      url = t('bug.url',
              title: t('bug.title', name: name),
              body: t('bug.body', path: request.path))

      redirect_to root_path, notice: t('errors.no_variants', name: name, url: url)
    end
  end

  def set_variant
    @variants = @theme.variants
    @variant =
      @variants.find_by(name: request.params[:variant]) ||
      @variants.first
  end

  def set_mode
    lang = request.params[:lang] || 'lisp'
    @mode = @modes.find_by(extension: lang) || @modes.find_by(name: 'Lisp')
  end

  def set_pagination
    mode_index = @modes.find_index @mode

    @previous_mode = @modes[mode_index - 1] unless mode_index.zero?
    @next_mode = @modes[mode_index + 1]

    index = @variants.find_index @variant
    @previous = @variants[index - 1] unless index.zero?
    @next = @variants[index + 1]
  end

  def theme_params
    params.require(:theme).permit(:name, :version)
  end
end

app/helpers/themes_helper.rb
# frozen_string_literal: true

module ThemesHelper
end

app/views/themes/_filters.html.haml
#filters
  .section#brightness
    .slider
      .bound Light
      %input{id: 'brightness_input',
             name: 'brightness',
             type: 'range',
             min: -1 + @lowest,
             max: @highest,
             step: 0.01,
             :"data-action" => "change->themes#adjustBrightness click->themes#handleDoubleClick",
             :"data-target" => "themes.slider"}
      .bound Dark

app/views/themes/_form.html.erb
<%= form_for(theme) do |f| %>
  <% if theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :version %>
    <%= f.text_field :version %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/themes/_theme_thumb.erb
<p> test </p>

app/views/themes/index.html.haml
#themes-list{data: { controller: 'themes' }}
  .flex.flex-row.flex-wrap.justify-center.-mx-2
    - unless @themes.any?
      .oops
        there are no themes yet. How strange.
    - @themes.each do |theme|
      .theme.group.transform.hover:scale-105.hover:-rotate-1.transition-all.hover:shadow-xl.rounded-md.overflow-hidden.shadow-md.sm:w-full.m-6{class: "lg:w-1/5 md:w-1/4"}
        = link_to theme do
          %img{src: url_for(theme.preview), alt: "preview for #{theme.name}", height: 300, width: 400}
          .meta.py-6.bg-white.h-full
            .px-6
              %span= theme.radical
              .text-xs.text-gray-500
                updated
                = time_ago_in_words(theme.version_to_datetime)
                ago
              - if theme.multi?
                %span.text-xs.text-gray-800
                  multiple variants ⭐
.pagination.my-6.text-center
  - if @previous
    = render partial: "components/button", locals: { link: @previous, text: "⟵ Previous page" }
  - if @next
    = render partial: "components/button", locals: { link: @next, text: "Next page ⟶" }

app/views/themes/show.html.haml
.theme.p-4{data: { controller: 'theme' }}
  %h2.text-2xl= @theme.name
  %h3.text-lg=@theme.description
  = link_to @url, @url, class: "underline text-sm text-gray-600 hover:text-black"

  %section
    .modes.selector.container.mx-auto.py-4
      - if @previous_mode
        = render 'components/button', link: theme_path(@theme, lang: @previous_mode.extension, variant: @variant), text: "⟵"
      %h3.inline-block.text-lg.p-4=@mode.name
      - if @next_mode
        = render 'components/button', link: theme_path(@theme, lang: @next_mode.extension, variant: @variant), text: "⟶"

    - if @theme.multi?
      .modes.selector.container.mx-auto.py-4
        - if @previous
          = render 'components/button', link: theme_path(@theme, variant: @previous, lang: @mode.extension), text: "⟵"
        %h3.inline-block.text-lg.p-4= @variant.name
        - if @next
          = render 'components/button', link: theme_path(@theme, variant: @next, lang: @mode.extension), text: "⟶"

  %img.rounded{src: url_for(@screenshot.image), height: 1200, width: 1600}

.container.mx-auto.text-center
  = render 'components/button', link: themes_path, text: '⟵ Back'