config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'themes#index'

  resources :themes, only: %i[index show], param: :name do
    resources :variants, param: :variant, only: :show
  end
end

app/models/variant.rb
# frozen_string_literal: true

require_relative '../../lib/parsing'

class Variant < ApplicationRecord
  belongs_to :theme
  has_many :screenshots, dependent: :destroy
  validates :name, presence: true, uniqueness: { scope: :theme } # rubocop:disable Rails/UniqueValidationWithoutIndex

  def to_param
    name
  end

  def parse!
    assets_path = File.join PeachMelpa::Parsing::SCREENSHOT_FOLDER, theme.name

    Dir.chdir(assets_path) do
      Dir.glob("#{name}_*").each do |name|
        mode = extract_mode name

        s = screenshots.create!(
          mode: mode
        )

        s.image.attach(
          io: File.open(File.join(assets_path, name)),
          filename: name
        )
      end
    end
  end

  def to_s
    name
  end

  def extract_mode(filename)
    ext = File.basename(filename, '.*').split('_').last

    Mode.find_by(extension: ext)
  end
end

app/controllers/variants_controller.rb
# frozen_string_literal: true

class VariantsController < ApplicationController
  def show
    theme = Theme.find_by(name: params[:theme_name])
    variant = theme.variants.find_by(name: params[:variant])
    mode = Mode.find_by(extension: params[:lang]) || Mode.first

    redirect_to theme_path(theme, variant: variant, lang: mode.extension)
  end
end

app/views/variants/show.html.haml
.theme-detail{data: { controller: 'theme' }}
  %h3.description
    = link_to @theme.description, @url, { class: "link" }
  %section.variants
    .modes.selector
      - if @previous_mode
        = link_to "⟵", { controller: "variants", action: "show", name: @variant.name, lang: @previous_mode.extension }, {class: "button"}
      - else
        = link_to "⟵", "#", { class: 'disabled button' }
      %h3.mode.button= @mode.name
      - if @next_mode
        = link_to "⟶", { controller: "variants", action: "show", name: @variant.name, lang: @next_mode.extension }, {class: "button"}
      - else
        %a.button.disabled
          ⟶
    - if @multi
      .variants.selector
        - if @previous
          = link_to "⟵", { controller: "variants", action: "show", name: @previous.name, lang: @mode.extension }, {class: "button"}
        - else
          = link_to "⟵", "#", { class: 'disabled button' }
        %h3.name.button= @variant.name
        - if @next
          = link_to "⟶", { controller: "variants", action: "show", name: @next.name, lang: @mode.extension }, {class: "button"}
        - else
          %a.button.disabled
            ⟶
    .gallery{data: { target: 'theme.gallery'}}
      %img{src: url_for(@screenshot.image)}

= link_to '⟵ Back', themes_path, { class: 'button back' }